### ISSUE TITLE
Instance Management

### ISSUE THREAD

**Issue by Nixotica** [hollow-cube/common#2]
Requirements:
* Framework for interfacing with instances stored in some external database
* Framework for managing instances in memory (Redis?)
* Basic methods using PostgreSQL to interface with the database
  * Query, sort by field, join two input tables on ID, etc
* Commands to create, delete, load, unload, save

Stretch Goals:
* Schematic management with similar requirements to above
  * Additionally, have a table relating schematic ID to instance ID + paste position (and orientation if necessary)

**Comment by mworzala** [comment]
Moved to project board
