### ISSUE TITLE
Schematics take a long time to load and save

### ISSUE THREAD

**Issue by Codestech1** [hollow-cube/common#38]
Title says all, when i load or save my schematic with worldedit it takes few ms, when i save or load schematic with hollow cube it takes a lot of time (in minutes), so i can't use it for minigames.

**Comment by mworzala** [comment]
Do you have an example schematic that takes minutes to load? And I assume this is running in an extremely resource bound environment? What is the configuration

**Comment by Codestech1** [comment]
Yeah i have one example schematic, i can send it on discord (Codestech#0001), I tried loading it on my vps and my laptop, both have good performance, i give 1 gb - 2gb for one minestom instance.
