### ISSUE TITLE
Issue with non-cubic structure or air block.

### ISSUE THREAD

**Issue by KrunkerPremium** [hollow-cube/common#46]
After further testing the schematic with the schematic Builder/Writer I found a issue that messes up the order in which blocks are stored. (Not the same problem than before).

hypothesis. Might be something related to the fact that we do not save AIR block... or not.

I tried removing the check for air 

        if (block.isAir()) {
            // If it's air, attempt to remove any existing value at that point.
            blockSet.remove(pos);
        } else {
            blockSet.put(pos, block);
        }
        
did not work.

useful information: it seems to happen only when the border of the structure is AIR or contains AIR.

but here is an example of the structure I tried to copy.
![2023-05-07_12 43 22](https://user-images.githubusercontent.com/128103081/236691418-37975812-69f9-4224-a9a0-969ed22aae96.png)

The emerald blocks are the two extremity of the schematic build.

here are the results
![2023-05-07_12 43 36](https://user-images.githubusercontent.com/128103081/236691444-e0f959fe-e82e-4aa6-b9ce-16739d035c57.png)

I haven't changed my code for saving the schematic.

PlayerClipboard playerClipboard = premiumAPI.getClipboard(p.getUuid());
                    Point pos1 = playerClipboard.getPos1();
                    Point pos2 = playerClipboard.getPos2();
                    playerClipboard.clear();
                    for (int x = Math.min(pos1.blockX(), pos2.blockX()); x <= Math.max(pos1.blockX(), pos2.blockX()); x++) {
                        for (int y = Math.min(pos1.blockY(), pos2.blockY()); y <= Math.max(pos1.blockY(), pos2.blockY()); y++) {
                            for (int z = Math.min(pos1.blockZ(), pos2.blockZ()); z <= Math.max(pos1.blockZ(), pos2.blockZ()); z++) {
                                Pos pos = new Pos(x, y, z);
                                playerClipboard.getBuilder().addBlock(pos, p.getInstance().getBlock(pos));
                            }
                        }
                    }
                    Schematic schematic = playerClipboard.getBuilder().build();
                    try {
                        File file = new File("./schematics/test.schem");
                        if (!file.exists()){
                            file.createNewFile();
                            p.sendMessage("Created New File");
                        }
                        SchematicWriter.write(schematic,file.toPath());
                        p.sendMessage("Success");
                    } catch (IOException e) {
                        p.sendMessage("Fail");
                        throw new RuntimeException(e);
                    }
                    
Thank you in advance this project is Amazing!!!

**Comment by mworzala** [comment]
Thank you as always for the report, I will take a look asap :)

**Comment by KrunkerPremium** [comment]
:) if you have any questions? lmk

**Comment by mworzala** [comment]
I believe this is fixed by #47, but I did find another case that is not handled well when looking into this.

I have not been able to track it down quite yet, nor am I quite sure whats causing it. Hopefully you will run into it and have some more info :D
